### ISSUE TITLE
Templates for TL Logs

### ISSUE THREAD

**Issue by Livvi** [DataManagementLab/bp-tool#10]
The Orga should be able to provide a template each week that is filled by the TLs

**Comment by bhaettasch** [comment]
Als initial des Log-Feldes? Zeitgesteuert oder indem man eine Einstellung im BP-Tool regelmäßig austauscht? Verschieden komplexe Möglichkeiten

**Comment by Livvi** [comment]
For TL Logs, add "Leitfragen der Woche:" field over the log form. Template Questions can be adapted by Orga Members in the Admin menu.
