### ISSUE TITLE
Migrations should be committed to repo

### ISSUE THREAD

**Issue by Jonas-July** [DataManagementLab/bp-tool#118]
Hi,
when the database models are changed, Django can create migrations for the database by running `manage.py makemigrations`. These migrations [should be committed into the codebase](https://docs.djangoproject.com/en/3.2/topics/migrations/). See further commentary [here](https://stackoverflow.com/questions/48376993/should-the-migrations-directory-in-a-django-project-should-be-pushed-to-the-git) and [here](https://stackoverflow.com/questions/28035119/should-i-be-adding-the-django-migration-files-in-the-gitignore-file).

I've noticed that some migrations for model changes are not contained in this repo. This necessitates running `makemigrations` locally, or even on a production server, which is generally discouraged.

A useful option is `--name` to explicitly name the migration, e.g. `manage.py makemigrations --name useful_name`

Once the missing migrations have been committed, this issue can be closed. After that it can serve as a reference.

**Comment by Livvi** [comment]
Thanks @Jonas-July!

@N-Lange please add the missing migrations to the repo :)

**Comment by Jonas-July** [comment]
This issue is not fixed on the `main` branch as of now (62d50f1b55a9a03b8b005fe902cecb609eac5564). Please make sure that issues that occur on the main branch are only closed once they are completed on the main branch.
