### ISSUE TITLE
presentation training (?)

### ISSUE THREAD

**Issue by urbanmatthias** [DataManagementLab/bp-tool#13]
In the past it was difficult for external presentation trainers to communicate with the students, because we weren't allowed to forward the students' mail addresses.

Maybe it makes sense to have a view for the (external) trainer that allows him/her to:
- Contact students
- See all appointments
- Move appointments
- Mark missing students
- Provide video feedback (maybe not)
- Update the groups (e.g. if a participant is sick and someone else shows up)

**Comment by bhaettasch** [comment]
Moodle-Zugriff für Trainer*in?

**Comment by Livvi** [comment]
erstmal nicht weiter relevant
