### ISSUE TITLE
Show past gradings

### ISSUE THREAD

**Issue by Jonas-July** [DataManagementLab/bp-tool#28]
- [x] The AG should be able to see his past gradings both on the grading page and on the success page \
- [x] The Orga team should be able to see past gradings per project \
- [ ] ~~Each grading must have a unique URL through which it can be accessed~~

Related to issue #5

**Comment by bhaettasch** [comment]
Zumindest für das Orga-Team könnte man das einfach mit auf die Detailseite für das Projekt packen, oder?

**Comment by Jonas-July** [comment]
So ähnlich wie die Logs? Im Prinzip sowas wie `include "bp/render_gradings.html" wäre leicht möglich. Man könnte zwar nicht editieren, aber man könnte sie sehen.

**Comment by bhaettasch** [comment]
Das wäre völlig ausreichend, ja. Zum Editieren gäbe es ja immer noch das Backend, aber in 99,irgendwas % der Fälle sollte es eh nicht nötig sein, da etwas zu editieren

**Comment by Jonas-July** [comment]
Wenn #27 gemergt wird, dann kann dieser Issue auch geschlossen werden.
